<!DOCTYPE html>
<html lang="en">

<head>
    @include('user.components.metadata')
    @stack('css')
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <link rel="stylesheet" href="/css/header.css">
    <script type="application/ld+json">
        {
            "@context": "https://schema.org",
            "@type": "CollegeOrUniversity",
            "name": "College Vihar",
            "alternateName": "Firstvite e-learning",
            "url": "https://collegevihar.com/",
            "logo": "https://collegevihar.com/public/images/logomini.png",
            "contactPoint": {
                "@type": "ContactPoint",
                "telephone": "9266585858",
                "contactType": "customer service",
                "contactOption": "TollFree",
                "areaServed": "IN",
                "availableLanguage": ["en","hi"]
            },
            "sameAs": [
                "https://www.instagram.com/collegevihar",
                "https://in.linkedin.com/in/college-vihar-7a49582b4"
            ]
        }
    </script>
</head>
@include('user.components.header')

<body>

    @yield('main')
    @include('user.components.footer')
    @include('user.components.go_to_top')
    <!-- Main Scripts -->
    <script src="{{ url('/js/utils.js') }}"></script>
    {{-- <script src="{{ url('/js/header.js') }}"></script> --}}
    @stack('script')
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-08Z5ZZCQ9H"></script>
    <script>
        window.assetBaseUrl = '{{ url('/') }}';
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'G-08Z5ZZCQ9H');
    </script>
</body>

</html>