<!DOCTYPE html>
<html lang="en">

<head>
    @include('user.components.metadata')
    @stack('css')
    <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
    <script type="application/ld+json">
        [

        ]
    </script>
</head>
@include('user.components.header')

<body>

    @yield('main')
    @include('user.components.footer')
    @include('user.components.go_to_top')
    <!-- Main Scripts -->
    <script src="{{ url('/js/utils.js') }}"></script>
    {{-- <script src="{{ url('/js/header.js') }}"></script> --}}
    @stack('script')
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-08Z5ZZCQ9H"></script>
    <script>
        window.assetBaseUrl = '{{ url('/') }}';
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'G-08Z5ZZCQ9H');
    </script>
</body>

</html>